services:
  demo:
    build: .
    image: advanced-topics-final-project-master-demo
    environment:
      NOPE_ZK_CHECK: "0"
      NOPE_ZK_ENFORCE: "0"
      NOPE_LOG_LEVEL: "DEBUG"
      PYTHONIOENCODING: "utf-8"
    # run init + simulate in one-shot
    command: [ "sh", "-lc", "python init_tls.py && python init_nope.py && python simulate.py" ]
    # if you want to reuse host tls/tokens instead of generating inside container,
    # uncomment the two lines below:
    # volumes:
    #   - ./tls:/app/tls
    #   - ./nope/tokens:/app/nope/tokens
